version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start:dev api-gateway
    environment:
      - NODE_ENV=development
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - JWT_SECRET=secret
    depends_on:
      - department-service
      - mongodb

  department-service:
    build:
      context: .
      dockerfile: apps/department-service/Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start:dev department-service
    environment:
      - NODE_ENV=development
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    command: mongod --bind_ip_all

volumes:
  mongodb_data:

networks:
  default:
    name: microservices-network