version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start:dev api-gateway
    environment:
      - NODE_ENV=development
    depends_on:
      - user-service

  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start:dev user-service
    environment:
      - NODE_ENV=development

networks:
  default:
    name: microservices-network